### ISSUE TITLE
allow publishing of URN:OID based attributes only

### ISSUE THREAD

**Issue by surfnet-niels** [OpenConext/OpenConext-serviceregistry#40]
SR currently has a switch[1] to only publish URN:MACE:DIR based attribtes, which are rather obsolute, but hey.
A similar feature is needed to allow only publishing URN:OID based attributes.

[1] "Do not add aliases of attributes"(default: Unchecked). 
Eg: Unset/unchecked gives both urn:mace:dir:attribute-def:cn and urn:oid:2.5.4.3. Checked gives only urn:mace:dir:attribute-def:cn.

**Comment by thijskh** [comment]
This repository is not used anymore; closing this issue in favour of the one filed in the janus repo.
